---
version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 150
    goconst:
      min-occurrences: 5
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 80
      tab-width: 4
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
        path: _test\.go
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - lll
        source: "`json:"
      - linters:
          - lll
        source: "`xml:"
      - linters:
          - lll
        source: "`yaml:"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
